### ISSUE TITLE
Crash on launch in release builds only

### ISSUE THREAD

**Issue by mtostenson** [f111fei/react-native-unity-view#79]
Unity version: 2018.2.1f1
React native version: 0.57.8

When running straight out of XCode, it works fine. However, creating a release IPA file results in an immediate crash on launch. We use fastlane to generate an IPA for beta testing, so we don't usually see this problem until then. I tested this using a blank react native project, and a blank unity project, and the crash is there. There are no useful crash logs unfortunately. Has anyone been able to publish an iOS release using this library?

Thanks

Here's the crash report:
`Thread 7 name:  com.facebook.react.JavaScript
Thread 7 Crashed:
0   libsystem_kernel.dylib        	0x00000001fbbbd104 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x00000001fbc3ca00 pthread_kill$VARIANT$armv81 + 296
2   libsystem_c.dylib             	0x00000001fbb14d78 abort + 140
3   libsystem_malloc.dylib        	0x00000001fbc11768 _malloc_put + 0
4   libsystem_malloc.dylib        	0x00000001fbc11924 malloc_report + 64
5   libsystem_malloc.dylib        	0x00000001fbc042d0 free + 376
6   libc++.1.dylib                	0x00000001fb1bf120 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string+ 258336 () + 32
7   UnityTest                     	0x0000000102de23a4 std::__1::__vector_base<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::~__vector_base() + 730020 (vector:451)
8   UnityTest                     	0x0000000103385214 facebook::react::ModuleRegistry::getConfig+ 6640148 (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 100
9   UnityTest                     	0x0000000103394168 facebook::react::JSCNativeModules::createModule+ 6701416 (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, OpaqueJSContext const*) + 292
10  UnityTest                     	0x0000000103393cc8 facebook::react::JSCNativeModules::getModule+ 6700232 (OpaqueJSContext const*, OpaqueJSString*) + 188
11  UnityTest                     	0x000000010338e85c OpaqueJSValue const* (*facebook::react::(anonymous namespace)::exceptionWrapMethod<&(facebook::react::JSCExecutor::getNativeModule(OpaqueJSValue*, OpaqueJSString*))>())(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSString*, OpaqueJSValue const**)::funcWrapper::call+ 6678620 (OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSString*, OpaqueJSValue const**) + 104
12  JavaScriptCore                	0x0000000203350404 JSC::JSCallbackObject<JSC::JSDestructibleObject>::getOwnPropertySlot+ 574468 (JSC::JSObject*, JSC::ExecState*, JSC::PropertyName, JSC::PropertySlot&) + 340
13  JavaScriptCore                	0x0000000203a354f0 llint_slow_path_get_by_id + 2008
14  JavaScriptCore                	0x0000000203328928 llint_entry + 11528
15  JavaScriptCore                	0x000000020332d134 llint_entry + 29972
16  JavaScriptCore                	0x000000020332d134 llint_entry + 29972
17  JavaScriptCore                	0x000000020332d134 llint_entry + 29972
18  JavaScriptCore                	0x000000020332d134 llint_entry + 29972
19  JavaScriptCore                	0x000000020332d134 llint_entry + 29972
20  JavaScriptCore                	0x0000000203325a1c vmEntryToJavaScript + 300
21  JavaScriptCore                	0x000000020399bfe4 JSC::Interpreter::executeProgram+ 7176164 (JSC::SourceCode const&, JSC::ExecState*, JSC::JSObject*) + 9620
22  JavaScriptCore                	0x0000000203b77218 JSC::evaluate+ 9122328 (JSC::ExecState*, JSC::SourceCode const&, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&) + 316
23  JavaScriptCore                	0x000000020334e634 JSEvaluateScript + 472
24  UnityTest                     	0x000000010336dad0 facebook::react::evaluateScript+ 6544080 (OpaqueJSContext const*, OpaqueJSString*, OpaqueJSString*) + 80
25  UnityTest                     	0x000000010338c918 facebook::react::JSCExecutor::loadApplicationScript+ 6670616 (std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 528
26  UnityTest                     	0x0000000103392ba4 std::__1::__function::__func<facebook::react::NativeToJsBridge::loadApplication(std::__1::unique_ptr<facebook::react::RAMBundleRegistry, std::__1::default_delete<facebook::react::RAMBundleRegistry> >, std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0, std::__1::allocator<facebook::react::NativeToJsBridge::loadApplication(std::__1::unique_ptr<facebook::react::RAMBundleRegistry, std::__1::default_delete<facebook::react::RAMBundleRegistry> >, std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0>, void (facebook::react::JSExecutor*)>::operator()+ 6695844 (facebook::react::JSExecutor*&&) + 144
27  UnityTest                     	0x0000000103393ba8 std::__1::function<void (facebook::react::JSExecutor*)>::operator()+ 6699944 (facebook::react::JSExecutor*) const + 40
28  UnityTest                     	0x000000010330c9cc facebook::react::tryAndReturnError(std::__1::function<void + 6146508 ()> const&) + 24
29  UnityTest                     	0x0000000103302528 facebook::react::RCTMessageThread::tryFunc(std::__1::function<void + 6104360 ()> const&) + 24
30  CoreFoundation                	0x00000001fbfb6408 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
31  CoreFoundation                	0x00000001fbfb5d08 __CFRunLoopDoBlocks + 272
32  CoreFoundation                	0x00000001fbfb1220 __CFRunLoopRun + 2376
33  CoreFoundation                	0x00000001fbfb05b8 CFRunLoopRunSpecific + 436
34  UnityTest                     	0x00000001032e36a4 +[RCTCxxBridge runRunLoop] + 264
35  Foundation                    	0x00000001fcad73b0 __NSThread__start__ + 1040
36  libsystem_pthread.dylib       	0x00000001fbc412fc _pthread_body + 128
37  libsystem_pthread.dylib       	0x00000001fbc4125c _pthread_start + 48
38  libsystem_pthread.dylib       	0x00000001fbc44d08 thread_start + 4
`

**Comment by alisherakb** [comment]
We've surfaced all the web and tried so many solutions. This finally worked for us!
Try to remove **Up Arrows** from all dependencies, i.e package.json.
**As an example:**
`"react-native-unity-view": "^1.2.1"`
**to:**
`"react-native-unity-view": "1.2.1"`

**Comment by mtostenson** [comment]
@alisherakb Interesting, so that fixed your release builds? I gave it a shot but it did not seem to change anything.

**Comment by alisherakb** [comment]
@mtostenson Yes, it solved the issue. Whenever we archive and install .ipa app it was crashing. We really tried every solution from the web and only it worked by accident, we tried to reproduce and it was causing the crash.

**Comment by alisherakb** [comment]
> @alisherakb Interesting, so that fixed your release builds? I gave it a shot but it did not seem to change anything.

Have you tried to archive .ipa file directly from XCode without Fastlane?

**Comment by mtostenson** [comment]
@alisherakb Yes, that is how I tested the empty test project, archived into IPA. May I ask what versions of React Native, Unity, Node, and this library are you using?

**Comment by alisherakb** [comment]
> @alisherakb Yes, that is how I tested the empty test project, archived into IPA. May I ask what versions of React Native, Unity, Node, and this library are you using?

Sure.
RN: 0.57.3
Unity: 2018.1.3f1
Node: v8.15 
RN unity view: 1.2.1

P.S. This issue was reproduced and fixed by following above-mentioned solution on Node v10.14.2

**Comment by mtostenson** [comment]
Thank you for the help. I'm still not able to get an IPA that doesn't crash. Have you tried using the current version of RN unity view?

**Comment by alisherakb** [comment]
> Thank you for the help. I'm still not able to get an IPA that doesn't crash. Have you tried using the current version of RN unity view?

No. Have you tried to downgrade?
Do you generate main.jsbundle before archiving the project? 

`react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios`

**Comment by alisherakb** [comment]
Our log is similiar.

`Dec 22 02:10:53 iPhone-7 ReportCrash(CrashReporterSupport)[4317] <Notice>: Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0:
0   libsystem_kernel.dylib        	0x00000001834a7de8 0x1834a7000 + 3560
1   libsystem_kernel.dylib        	0x00000001834a7c60 0x1834a7000 + 3168
2   CoreFoundation                	0x00000001839eae40 0x1838fd000 + 974400
3   CoreFoundation                	0x00000001839e8908 0x1838fd000 + 964872
4   CoreFoundation                	0x0000000183908da8 0x1838fd000 + 48552
5   GraphicsServices              	0x00000001858ee020 0x1858e3000 + 45088
6   UIKit                         	0x000000018d928758 0x18d60b000 + 3266392
7   SpacerProduction              	0x0000000100edba50 0x100ed4000 + 31312
8   libdyld.dylib                 	0x0000000183399fc0 0x183399000 + 4032
Dec 22 02:10:53 iPhone-7 ReportCrash(CrashReporterSupport)[4317] <Notice>: Thread 1:
0   libsystem_pthread.dylib       	0x0000000183667b04 0x183667000 + 2820
Dec 22 02:10:53 iPhone-7 ReportCrash(CrashReporterSupport)[4317] <Notice>: Thread 2:
0   libsystem_kernel.dylib        	0x00000001834c9d78 0x1834a7000 + 142712
1   libsystem_pthread.dylib       	0x0000000183667eb4 0x183667000 + 3764
2   libsystem_pthread.dylib       	0x0000000183667b08 0x183667000 + 2824
Dec 22 02:10:53 iPhone-7 ReportCrash(CrashReporterSupport)[4317] <Notice>: Thread 3:
0   libsystem_kernel.dylib        	0x00000001834c9d78 0x1834a7000 + 142712
1   libsystem_pthread.dylib       	0x00000001836680a0 0x183667000 + 4256
2   libsystem_pthread.dylib       	0x0000000183667b08 0x183667000 + 2824`

**Comment by JanOwiesniak** [comment]
I had problems with iOS Ad-Hoc / App Store Builds too. The app crashed immediately without any useful logs. Setting some compiler flags in XCode worked for me. You could give it a try.

**ios/rnunitydemo.xcodeproj/project.pbxproj**

```
COPY_PHASE_STRIP = YES;
ENABLE_BITCODE = NO;
STRIP_INSTALLED_PRODUCT
```

**Comment by mtostenson** [comment]
@JanOwiesniak I think you solved it. Thank you, I've been trying to fix this for probably too long.

**Comment by mtostenson** [comment]
This probably points to a larger underlying issue. @f111fei do you have any idea why this library would require setting "Strip Linked Product" to NO in order to avoid this crash?

**Comment by mtostenson** [comment]
@JanOwiesniak We found the problem has reappeared in iOS 12.1 even with the workaround. Is your app working on this version?

**Comment by richardlinxj** [comment]
Have you solved this issue？

**Comment by richardlinxj** [comment]
@mtostenson  Have you solved in iOS12.1 ？I have the same issue.

**Comment by peterfei** [comment]
We also have the same issue at iphone XS MAX in ios 12.1.4 also ,still crashed, any idea?

**Comment by mtostenson** [comment]
@richardlinxj @peterfei I was able to narrow down where the crash happens in the React Native c++ code. [Here's the issue on the React Native Repo](https://github.com/facebook/react-native/issues/23465). I included a description of how to avoid the crash. In short, you need to hold a reference to the vector that is returned from ModuleRegistry::moduleNames, I just added it as a field in the ModuleRegistry class and that seemed to work. Please join in on the discussion over there.

**Comment by peterfei** [comment]
@mtostenson  Thanks for reply , could u give me more information for it ,or some code for  
> just added it as a field in the ModuleRegistry class

**Comment by mtostenson** [comment]
> @mtostenson Thanks for reply , could u give me more information for it ,or some code for
> 
> > just added it as a field in the ModuleRegistry class

Sure. Add this to ModuleRegistry.h:
`std::vector<std::string> moduleNamesVec_;`

Then in ModuleRegistry.cpp in the getConfig function, change the line
`moduleNames();` into `moduleNamesVec_ = moduleNames();`

**Comment by peterfei** [comment]
@mtostenson  okay,let me try ~ 
thank  u for a million.

**Comment by mtostenson** [comment]
> @mtostenson okay,let me try ~
> thank u for a million.

No problem, please let me know if this does anything.

**Comment by JanOwiesniak** [comment]
> @JanOwiesniak We found the problem has reappeared in iOS 12.1 even with the workaround. Is your app working on this version?

@mtostenson [this](https://github.com/f111fei/react-native-unity-view/issues/79#issuecomment-453732223) workaround worked quite well until iPhone XS Max iOS 12.1.4

---

@mtostenson thanks for [the](https://github.com/f111fei/react-native-unity-view/issues/79#issuecomment-464965813) approach, i will give it a try.

**Comment by JanOwiesniak** [comment]
@mtostenson i changed following lines in react native (is this correct?)

![screen shot 2019-02-19 at 12 00 30](https://user-images.githubusercontent.com/213214/53014759-b1b1fe80-3449-11e9-87c7-e71fa8bc31d3.png)

And tested it via TestFlight on following device:

>  12.1.4 (16D57)
>  iPhone XS

The app still crashes BUT i have a crash report now (which i did not receive before)

```
Crashed: com.facebook.react.JavaScript
0  ???                            0x238e390e4 (Missing)
1  ???                            0x238eb1afc (Missing)
2  ???                            0x10d78238d8ffb0 (Missing)
3  ???                            0x68b58238e8ec7c (Missing)
4  ???                            0x15cb8238e8ee48 (Missing)
5  ???                            0x43980238e802c0 (Missing)
6  ???                            0x79468238471980 (Missing)
7  ???                            0x6426810307f168 (Missing)
8  rnunitydemo                    0x103db8844 facebook::react::ModuleRegistry::getConfig(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
9  rnunitydemo                    0x103dc70d4 facebook::react::JSCNativeModules::createModule(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, OpaqueJSContext const*)
10 rnunitydemo                    0x103dc6c34 facebook::react::JSCNativeModules::getModule(OpaqueJSContext const*, OpaqueJSString*)
11 rnunitydemo                    0x103dc1840 OpaqueJSValue const* (*facebook::react::(anonymous namespace)::exceptionWrapMethod<&(facebook::react::JSCExecutor::getNativeModule(OpaqueJSValue*, OpaqueJSString*))>())(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSString*, OpaqueJSValue const**)::funcWrapper::call(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSString*, OpaqueJSValue const**)
12 JavaScriptCore                 0x24074083c JSC::JSCallbackObject<JSC::JSDestructibleObject>::getOwnPropertySlot(JSC::JSObject*, JSC::ExecState*, JSC::PropertyName, JSC::PropertySlot&)
13 ???                            0x300c8240e5ec24 (Missing)
14 ???                            0x30c60240716554 (Missing)
15 ???                            0x57a7024071b39c (Missing)
16 ???                            0xa82024071b39c (Missing)
17 ???                            0x29c2824071b39c (Missing)
18 ???                            0x7aae024071b39c (Missing)
19 ???                            0xa7824071b39c (Missing)
20 ???                            0x78f9824071339c (Missing)
21 ???                            0x5cf18240db4cc4 (Missing)
22 ???                            0x43e80240fa7ad0 (Missing)
23 ???                            0x331e824073e73c (Missing)
24 ???                            0x38fa0103da1538 (Missing)
25 rnunitydemo                    0x103dbf8fc facebook::react::JSCExecutor::loadApplicationScript(std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)
26 rnunitydemo                    0x103dc5b70 std::__1::__function::__func<facebook::react::NativeToJsBridge::loadApplication(std::__1::unique_ptr<facebook::react::RAMBundleRegistry, std::__1::default_delete<facebook::react::RAMBundleRegistry> >, std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0, std::__1::allocator<facebook::react::NativeToJsBridge::loadApplication(std::__1::unique_ptr<facebook::react::RAMBundleRegistry, std::__1::default_delete<facebook::react::RAMBundleRegistry> >, std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0>, void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*&&)
27 rnunitydemo                    0x103b8d298 std::__1::function<void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*) const (functional:1913)
28 rnunitydemo                    0x103d407bc facebook::react::tryAndReturnError(std::__1::function<void ()> const&)
29 rnunitydemo                    0x103d36400 facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&)
30 CoreFoundation                 0x23923c354 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
31 ???                            0xc7823923bc38 (Missing)
32 ???                            0x1ca18239236f14 (Missing)
33 ???                            0x63302392362e8 (Missing)
34 ???                            0x3a590103d176c4 (Missing)
35 Foundation                     0x239c38fc0 -[NSThread main]
36 ???                            0x14e88239d75c44 (Missing)
37 ???                            0x37000238eb0974 (Missing)
38 ???                            0x11100238eb08d0 (Missing)
39 ???                            0x4a400238eb8ddc (Missing)
```

---

Has anyone any idea what's the issue here and how to solve it? We are already using this in production so this _discovery_ is really painful for us right now :(

**Comment by mtostenson** [comment]
> @mtostenson i changed following lines in react native (is this correct?)
> 
> ![screen shot 2019-02-19 at 12 00 30](https://user-images.githubusercontent.com/213214/53014759-b1b1fe80-3449-11e9-87c7-e71fa8bc31d3.png)
> 
> These are crash logs without the above patch. For whatever reasons i don't receive crashlogs anymore. App still does not boot on iPhone XS.
> 
> # Crashlog A
> ```
> Crashed: com.facebook.react.JavaScript
> 0  ???                            0x238e390e4 (Missing)
> 1  ???                            0x238eb1afc (Missing)
> 2  ???                            0x63240238d8ffb0 (Missing)
> 3  ???                            0x66ca8238e8ec7c (Missing)
> 4  ???                            0x67bb8238e8ee48 (Missing)
> 5  ???                            0x7d8a8238e802c0 (Missing)
> 6  ???                            0xfa0238471980 (Missing)
> 7  ???                            0x4e858102c9f168 (Missing)
> 8  rnunitydemo                    0x1039d8844 facebook::react::ModuleRegistry::getConfig(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
> 9  rnunitydemo                    0x1039e70d4 facebook::react::JSCNativeModules::createModule(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, OpaqueJSContext const*)
> 10 rnunitydemo                    0x1039e6c34 facebook::react::JSCNativeModules::getModule(OpaqueJSContext const*, OpaqueJSString*)
> 11 rnunitydemo                    0x1039e1840 OpaqueJSValue const* (*facebook::react::(anonymous namespace)::exceptionWrapMethod<&(facebook::react::JSCExecutor::getNativeModule(OpaqueJSValue*, OpaqueJSString*))>())(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSString*, OpaqueJSValue const**)::funcWrapper::call(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSString*, OpaqueJSValue const**)
> 12 ???                            0x24074083c (Missing)
> 13 ???                            0x71618240e5ec24 (Missing)
> 14 ???                            0x210a8240716554 (Missing)
> 15 ???                            0x7dcf824071b39c (Missing)
> 16 ???                            0x7503824071b39c (Missing)
> 17 ???                            0x6047024071b39c (Missing)
> 18 ???                            0x979024071b39c (Missing)
> 19 ???                            0x14da824071b39c (Missing)
> 20 ???                            0x5171024071339c (Missing)
> 21 ???                            0x4d60240db4cc4 (Missing)
> 22 ???                            0x5f6b0240fa7ad0 (Missing)
> 23 ???                            0x885824073e73c (Missing)
> 24 ???                            0x781801039c1538 (Missing)
> 25 rnunitydemo                    0x1039df8fc facebook::react::JSCExecutor::loadApplicationScript(std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)
> 26 rnunitydemo                    0x1039e5b70 std::__1::__function::__func<facebook::react::NativeToJsBridge::loadApplication(std::__1::unique_ptr<facebook::react::RAMBundleRegistry, std::__1::default_delete<facebook::react::RAMBundleRegistry> >, std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0, std::__1::allocator<facebook::react::NativeToJsBridge::loadApplication(std::__1::unique_ptr<facebook::react::RAMBundleRegistry, std::__1::default_delete<facebook::react::RAMBundleRegistry> >, std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0>, void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*&&)
> 27 rnunitydemo                    0x1037ad298 std::__1::function<void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*) const (functional:1913)
> 28 rnunitydemo                    0x1039607bc facebook::react::tryAndReturnError(std::__1::function<void ()> const&)
> 29 rnunitydemo                    0x103956400 facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&)
> 30 ???                            0x23923c354 (Missing)
> 31 ???                            0x1fa1823923bc38 (Missing)
> 32 ???                            0x185b0239236f14 (Missing)
> 33 ???                            0x4ea202392362e8 (Missing)
> 34 ???                            0x2b3e81039376c4 (Missing)
> 35 ???                            0x239c38fc0 (Missing)
> 36 ???                            0x4a270239d75c44 (Missing)
> 37 ???                            0x4cfb8238eb0974 (Missing)
> 38 ???                            0x591f8238eb08d0 (Missing)
> 39 ???                            0x3ffc0238eb8ddc (Missing)
> ```
> # Crashlog B
> ```
> Crashed: com.facebook.react.JavaScript
> 0  ???                            0x238e390e4 (Missing)
> 1  ???                            0x238eb1afc (Missing)
> 2  ???                            0x10d78238d8ffb0 (Missing)
> 3  ???                            0x68b58238e8ec7c (Missing)
> 4  ???                            0x15cb8238e8ee48 (Missing)
> 5  ???                            0x43980238e802c0 (Missing)
> 6  ???                            0x79468238471980 (Missing)
> 7  ???                            0x6426810307f168 (Missing)
> 8  rnunitydemo                    0x103db8844 facebook::react::ModuleRegistry::getConfig(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
> 9  rnunitydemo                    0x103dc70d4 facebook::react::JSCNativeModules::createModule(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, OpaqueJSContext const*)
> 10 rnunitydemo                    0x103dc6c34 facebook::react::JSCNativeModules::getModule(OpaqueJSContext const*, OpaqueJSString*)
> 11 rnunitydemo                    0x103dc1840 OpaqueJSValue const* (*facebook::react::(anonymous namespace)::exceptionWrapMethod<&(facebook::react::JSCExecutor::getNativeModule(OpaqueJSValue*, OpaqueJSString*))>())(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSString*, OpaqueJSValue const**)::funcWrapper::call(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSString*, OpaqueJSValue const**)
> 12 JavaScriptCore                 0x24074083c JSC::JSCallbackObject<JSC::JSDestructibleObject>::getOwnPropertySlot(JSC::JSObject*, JSC::ExecState*, JSC::PropertyName, JSC::PropertySlot&)
> 13 ???                            0x300c8240e5ec24 (Missing)
> 14 ???                            0x30c60240716554 (Missing)
> 15 ???                            0x57a7024071b39c (Missing)
> 16 ???                            0xa82024071b39c (Missing)
> 17 ???                            0x29c2824071b39c (Missing)
> 18 ???                            0x7aae024071b39c (Missing)
> 19 ???                            0xa7824071b39c (Missing)
> 20 ???                            0x78f9824071339c (Missing)
> 21 ???                            0x5cf18240db4cc4 (Missing)
> 22 ???                            0x43e80240fa7ad0 (Missing)
> 23 ???                            0x331e824073e73c (Missing)
> 24 ???                            0x38fa0103da1538 (Missing)
> 25 rnunitydemo                    0x103dbf8fc facebook::react::JSCExecutor::loadApplicationScript(std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)
> 26 rnunitydemo                    0x103dc5b70 std::__1::__function::__func<facebook::react::NativeToJsBridge::loadApplication(std::__1::unique_ptr<facebook::react::RAMBundleRegistry, std::__1::default_delete<facebook::react::RAMBundleRegistry> >, std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0, std::__1::allocator<facebook::react::NativeToJsBridge::loadApplication(std::__1::unique_ptr<facebook::react::RAMBundleRegistry, std::__1::default_delete<facebook::react::RAMBundleRegistry> >, std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0>, void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*&&)
> 27 rnunitydemo                    0x103b8d298 std::__1::function<void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*) const (functional:1913)
> 28 rnunitydemo                    0x103d407bc facebook::react::tryAndReturnError(std::__1::function<void ()> const&)
> 29 rnunitydemo                    0x103d36400 facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&)
> 30 CoreFoundation                 0x23923c354 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
> 31 ???                            0xc7823923bc38 (Missing)
> 32 ???                            0x1ca18239236f14 (Missing)
> 33 ???                            0x63302392362e8 (Missing)
> 34 ???                            0x3a590103d176c4 (Missing)
> 35 Foundation                     0x239c38fc0 -[NSThread main]
> 36 ???                            0x14e88239d75c44 (Missing)
> 37 ???                            0x37000238eb0974 (Missing)
> 38 ???                            0x11100238eb08d0 (Missing)
> 39 ???                            0x4a400238eb8ddc (Missing)
> ```
> Has anyone any idea what's the issue here and how to solve it? We are already using this in production so this _discovery_ is really painful for us right now :(

I feel your pain on that, our releases have been blocked as well. Your hot fix looks correct, I'm surprised it didn't have the same result for you. I have another suggestion for you, it's not pretty but it can be effective. Looking at your crash log, we should focus on ModuleRegistry::GetConfig. Try putting in a logging line after each statement in that function to find the exact line that result in the crash. Example:
`syslog(LOG_ERR, "TESTING: ModuleRegistry::getConfig 1");`
and increment the number at the end with each line. This is how I was able to find our "fix." Just open up the device console and filter on TESTING when you run the production build. I hope this helps.

**Comment by JanOwiesniak** [comment]
@mtostenson thanks for the debugging approach. Sadly i can't run the app on a simulator because we are using a [3rd party library](https://library.vuforia.com/articles/Solution/Getting-Started-with-Vuforia-for-iOS-Development) which can not run on the simulator:

> Vuforia Engine applications must be deployed to a device to run; they cannot be run in the iOS simulator. You must enroll in the iOS Developer program to deploy applications to an iOS device.

And i don't have access to this particular device in any physical way. Do you have any other idea how to pin that bug down without access to a physical device or the simulator :)

"puts debugging" would mean:

1. Add debug statement
2. Archive App via XCode
3. Upload to Apple App Store Connect (wait ~ 10 minutes until app is "processed")
4. Deploy App via TestFlight
5. Call someone who has a iPhone XS, tell him to download the new build via TestFlight and start it
6. Hope Crashlytics catches the exception (which it does not for whatever reasons in some cases)
7. Go back to step 1

**Comment by JanOwiesniak** [comment]
**Sidenote**

I just stumbled across [Firebase Test Lab](https://firebase.google.com/docs/test-lab/ios/firebase-console) and will give it a try. I seems to remove a lot of time consuming steps mentioned earlier.

**Comment by JanOwiesniak** [comment]
**Update**

Firebase Test Lab does not include XS or XR models 🤦‍♂️ 

![test-lab](https://user-images.githubusercontent.com/213214/53038125-3b7abf80-347c-11e9-85ea-8d551274172d.png)

**Comment by peterfei** [comment]
@mtostenson @JanOwiesniak  now i could run it under iPhone XS Max iOS 12.1.4,which use react-native patch yesterday.

**Comment by JanOwiesniak** [comment]
@peterfei which of [these](https://github.com/facebook/react-native/commits/master) commits include the fix?

**Comment by peterfei** [comment]
not found commits from issues, but u reply here like this:

![](https://user-images.githubusercontent.com/213214/53014759-b1b1fe80-3449-11e9-87c7-e71fa8bc31d3.png)

**Comment by JanOwiesniak** [comment]
This works for you? Could you tell me a bit more about your dependencies?

`react-native info` and current `react-native-unity-view` would be a great help

**Comment by daijiangping** [comment]
hello!

**Comment by Lance-Mao** [comment]
Onlookers !!!

**Comment by peterfei** [comment]
Sure, 
`
SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27
        Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.0 => 0.57.0
    npmGlobalPackages:
      react-native-unity-view: 1.3.3
      react-native-video: 4.3.1
`

**Comment by JanOwiesniak** [comment]
**react-native info**

```
  React Native Environment Info:
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        Build Tools: 23.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.1, 28.0.3
        API Levels: 21, 23, 24, 25, 26, 27, 28
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.0 => 0.57.0
```

**package.json**

`"react-native-unity-view": "^1.3.2"`

---

I'm still on `react-native-unity-view` v1.3.2, everything else looks pretty much the same. The only difference between 1.3.2 and 1.3.3 seems to be [this](https://github.com/f111fei/react-native-unity-view/commit/07b017e9b408ad6710d91961f4b7a01a0ade14f0) android related commit so i guess this is not the issue here.

**Comment by peterfei** [comment]
Strange,i'm sure only change the code by this patch......

**Comment by JanOwiesniak** [comment]
I just received a fresh crash report from Crashlytics. This one look different to me than the [previous](https://github.com/f111fei/react-native-unity-view/issues/79#issuecomment-465110101) crashes. Am i still hunting the same bug here or is this something new? I'm a bit lost here right now. Any feedback highly appreciated.

**crash_info_entry_0**

```
abort() called
```

**crash_info_entry_1**

```
rnunitydemo(7356,0x16b713000) malloc: *** error for object 0x10d82c460: pointer being freed was not allocated
```

**stacktrace**

iOS: 12.1.4 (16D57)
Device: iPhone XS

```
Crashed: com.google.firebase.firestore
0  libsystem_kernel.dylib         0x238e390e4 __pthread_kill + 8
1  libsystem_pthread.dylib        0x238eb1afc pthread_kill + 300
2  ???                            0x4aaf0238d8ffb0 (Missing)
3  ???                            0x60cd8238e8ec7c (Missing)
4  ???                            0x9bd8238e8ee48 (Missing)
5  ???                            0x2b690238e802c0 (Missing)
6  ???                            0x5839823847208c (Missing)
7  ???                            0x37828105696b40 (Missing)
8  rnunitydemo                    0x105696d2c firebase::firestore::local::LevelDbTransaction::Iterator::Seek(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (leveldb_transaction.cc:83)
9  rnunitydemo                    0x105634c38 -[FSTLevelDBMutationQueue allMutationBatchesAffectingDocumentKeys:] (memory:2567)
10 rnunitydemo                    0x10563d360 -[FSTLocalDocumentsView documentsForKeys:] (FSTLocalDocumentsView.mm:84)
11 rnunitydemo                    0x105642a2c -[FSTLocalStore applyRemoteEvent:] (FSTLocalStore.mm:307)
12 rnunitydemo                    0x105678020 -[FSTSyncEngine applyRemoteEvent:] (FSTSyncEngine.mm:352)
13 rnunitydemo                    0x1056693a8 -[FSTRemoteStore raiseWatchSnapshotWithSnapshotVersion:] (FSTRemoteStore.mm:416)
14 rnunitydemo                    0x105668cb0 -[FSTRemoteStore watchStreamDidChange:snapshotVersion:] (FSTRemoteStore.mm:333)
15 rnunitydemo                    0x10569c3d4 firebase::firestore::remote::bridge::WatchStreamDelegate::NotifyDelegateOnChange(FSTWatchChange*, firebase::firestore::model::SnapshotVersion const&) (remote_objc_bridge.mm:306)
16 rnunitydemo                    0x1056a42d8 firebase::firestore::remote::WatchStream::NotifyStreamResponse(grpc::ByteBuffer const&) (watch_stream.mm:93)
17 rnunitydemo                    0x1056a015c firebase::firestore::remote::Stream::OnStreamRead(grpc::ByteBuffer const&) (memory:2583)
18 rnunitydemo                    0x105691238 std::__1::function<void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*) const (functional:1913)
19 rnunitydemo                    0x10568bbdc std::__1::function<void (bool, firebase::firestore::remote::GrpcCompletion const*)>::operator()(bool, firebase::firestore::remote::GrpcCompletion const*) const (functional:1913)
20 rnunitydemo                    0x10568bac8 std::__1::__function::__func<firebase::firestore::remote::GrpcCompletion::Complete(bool)::$_0, std::__1::allocator<firebase::firestore::remote::GrpcCompletion::Complete(bool)::$_0>, void ()>::operator()() (grpc_completion.cc:69)
21 rnunitydemo                    0x1055f9118 firebase::firestore::util::AsyncQueue::ExecuteBlocking(std::__1::function<void ()> const&) (atomic:921)
22 rnunitydemo                    0x10560014c firebase::firestore::util::internal::DispatchAsync(NSObject<OS_dispatch_queue>*, std::__1::function<void ()>&&)::$_0::__invoke(void*) (executor_libdispatch.mm:58)
23 libdispatch.dylib              0x238cb1134 _dispatch_client_callout + 20
24 ???                            0x75640238cb864c (Missing)
25 ???                            0x43e78238cb9194 (Missing)
26 ???                            0x1a6a8238cc1480 (Missing)
27 ???                            0x71b98238eb2b20 (Missing)
28 ???                            0x2358238eb8dd4 (Missing)
```

**Comment by JanOwiesniak** [comment]
@peterfei @mtostenson three more questions which might help me to get closer to the problem:

1. Are you using XCodes new build system or the legacy build system? (i'm using the old build system)
2. Are you on macOS High Sierra or macOS Mojave? (i'm on High Sierra)
3. Which Unity Version you are using? (me: 2018.2.14f1)

**Comment by peterfei** [comment]
@JanOwiesniak 
  1. i used the legacy build system
  2. On maxOS High Sierra.
  3. Unity version was `2017.2.0f3`

**Comment by mtostenson** [comment]
@JanOwiesniak 
1. Legacy build system
2. High Sierra
3. 2018.2.1f1 before, but today after I updating to 2018.3.6f1 I am no longer getting a crash on start. This might be a seperate issue to the one I was describing before, but I would suggest trying to this version along with 1.3.3 of this library. You'll probably run into a couple of issues:
SplashScreen.mm you'll need to change `#include "Classes/Unity/UnitySharedDecls.h"` to `#include "Unity/UnitySharedDecls.h"`
You'll also need to remove references to DynamicLibEngineAPI-functions.h and DynamicLibEngineAPI.mm. [More about that issue here.](DynamicLibEngineAPI-functions.h && DynamicLibEngineAPI.mm)
If this helps you too I'll probably open a PR to fix those issues and add support for this Unity version.

**Comment by JanOwiesniak** [comment]
@peterfei @mtostenson thanks for your help.

I will update react-native-unity-view to 1.3.3. and Unity to 2018.3.6. Let's see if this fixes the issue. @mtostenson special thanks for the hotfixes for upcoming issue i will run into :)

**Comment by peterfei** [comment]
@mtostenson  when i used Unity to 2018.3.6, 
show some error like 
```

: "_OBJC_CLASS_$_AVPlayerViewController", referenced from:

: Objc-class-ref in FullScreenVideoPlayer.o

: Symbol(s) not found for architecture arm64

: Linker command failed with exit code 1 (use -v to see invocation)


```

any idea?

**Comment by peterfei** [comment]
My fault,should add AVKit.framework ....

**Comment by JanOwiesniak** [comment]
**This is how i fixed it (in a nutshell)**

1. Remove node_modules
2. Reinstall node_modues via yarn
3. Update Unity from 2018.2.14f1 to 2018.3.6f1
4. Build UnityExport
5. Patch UnityExport (https://github.com/jiulongw/swift-unity/pull/120#issuecomment-456315250, https://github.com/f111fei/react-native-unity-view/issues/79#issuecomment-465819733)
6. Update react-native-unity-view to 1.3.3
7. Update react-native to 0.57.8
8. Patch react-native `moduleNames()` (https://github.com/f111fei/react-native-unity-view/issues/79#issuecomment-465110101)

---

@peterfei @mtostenson thanks again for your support.

**Comment by alisherakb** [comment]
> @JanOwiesniak
> 
> 1. Legacy build system
> 2. High Sierra
> 3. 2018.2.1f1 before, but today after I updating to 2018.3.6f1 I am no longer getting a crash on start. This might be a seperate issue to the one I was describing before, but I would suggest trying to this version along with 1.3.3 of this library. You'll probably run into a couple of issues:
>    SplashScreen.mm you'll need to change `#include "Classes/Unity/UnitySharedDecls.h"` to `#include "Unity/UnitySharedDecls.h"`
>    You'll also need to remove references to DynamicLibEngineAPI-functions.h and DynamicLibEngineAPI.mm. [More about that issue here.](https://github.com/jiulongw/swift-unity/pull/120#issuecomment-456315250)
>    If this helps you too I'll probably open a PR to fix those issues and add support for this Unity version.

@mtostenson @JanOwiesniak 
Hey guys, I'm following your solutions but even not able to run the project in debug:  
<img width="802" alt="Screenshot 2019-03-13 at 11 41 13 PM" src="https://user-images.githubusercontent.com/26904008/54316468-873b0780-45e9-11e9-88a9-ef4105a21734.png">

Have you ever experienced this issue?

Unity -v: 2018.3.2
"react-native": "0.58.6"

**Comment by mtostenson** [comment]
Did you set up the xcconfig correctly as it shows in the integration guide? It could be that your header search paths aren't set up right.

**Comment by alisherakb** [comment]
> Did you set up the xcconfig correctly as it shows in the integration guide? It could be that your header search paths aren't set up right.

Thanks for the reply.
Actually, I changed my xcconfig a bit, followed this commit https://github.com/jiulongw/swift-unity/pull/120/commits/55826261738d7adebe011a7474eec7aa5b898adc

Otherwise, I'm getting a different error on following this library's xcconfig:
<img width="1280" alt="Screenshot 2019-03-13 at 11 53 46 PM" src="https://user-images.githubusercontent.com/26904008/54317432-ccf8cf80-45eb-11e9-8279-b3aa4fc13e13.png">

**Comment by hoxily** [comment]
I fixed the same crash issue by remove `std::move` function call around `name` variable in `ModuleRegistry::moduleNames()` function body.

**Comment by OgieBen** [comment]
@alisherakb I am equally experiencing the same issue. Please, how did you fix yours?

**Comment by alisherakb** [comment]
@OgieBen Hi, can you provide more details about the issue? 
My last comments here were about the error on running Unity3D 2018.2+ and react-native-unity-view.

**Comment by OgieBen** [comment]
@alisherakb I was only able to build after downgrading to an older version of Unity 2018.1f2.

However, my initial version of Unity was v2018.3.13 when I encountered the error. 
react-native-unity-view: v1.3.3

I also made changes to the library's xcconfig file

**Comment by alisherakb** [comment]
> @alisherakb I was only able to build after downgrading to an older version of Unity 2018.1f2.
> 
> However, my initial version of Unity was v2018.3.13 when I encountered the error.
> react-native-unity-view: v1.3.3
> 
> I also made changes to the library's xcconfig file

In my case downgrading `react-native-unity-view` to `1.2.1 ` solved the issue. 
The error was occurring because of the `UnityNativeModule.h` that appeared in newer versions.

**Comment by psyrenpark** [comment]
same isuue.
I solved it in the following way.

"Undefined symbols for architecture arm64: _OBJC_CLASS_$_AVPlayerViewController"
-> 
1: Visit Build phases
2: Add AVKit.framework

Unable to use '@try' with Objective-C exceptions disabled
->
1: Project Navigator -> select project or target -> build settings -> Enable Objective-C Exceptions 
https://stackoverflow.com/questions/11855382/how-to-enable-objective-c-exceptions-on-xcode-4-2


react-native info

info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
      Memory: 1.06 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - /usr/local/Cellar/node/11.14.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1

**Comment by techistoner** [comment]
> We also have the same issue at iphone XS MAX in ios 12.1.4 also ,still crashed, any idea?

yes  i have the same issue at xs max and ipad pro

**Comment by techistoner** [comment]
> I had problems with iOS Ad-Hoc / App Store Builds too. The app crashed immediately without any useful logs. Setting some compiler flags in XCode worked for me. You could give it a try.
> 
> **ios/rnunitydemo.xcodeproj/project.pbxproj**
> 
> ```
> COPY_PHASE_STRIP = YES;
> ENABLE_BITCODE = NO;
> STRIP_INSTALLED_PRODUCT = NO;
> ```

i have try it ,but still crash in xs max & ipad pro ,but no crash in iphone x & iphone 8plus

**Comment by techistoner** [comment]
Thread 6 name:  com.facebook.react.JavaScript
Thread 6 Crashed:
0   libsystem_kernel.dylib        	0x0000000202b540cc __pthread_kill + 8
1   libsystem_c.dylib             	0x0000000202aad14c abort + 144
2   libsystem_malloc.dylib        	0x0000000202ba8c84 _malloc_put + 0
3   libsystem_malloc.dylib        	0x0000000202ba8e4c malloc_report + 64
4   libsystem_malloc.dylib        	0x0000000202b9a520 free + 432
5   libc++.1.dylib                	0x000000020219559c std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string+ 267676 () + 36
6   hiuni                         	0x0000000104aa0a64 std::__1::__vector_base<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::~__vector_base() + 1411684 (vector:451)
7   hiuni                         	0x0000000105341f20 facebook::react::ModuleRegistry::getConfig+ 10460960 (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 100
8   hiuni                         	0x00000001053503c0 facebook::react::JSCNativeModules::createModule+ 10519488 (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, OpaqueJSContext const*) + 268
9   hiuni                         	0x000000010534fff4 facebook::react::JSCNativeModules::getModule+ 10518516 (OpaqueJSContext const*, OpaqueJSString*) + 184
10  hiuni                         	0x000000010534ae34 OpaqueJSValue const* (*facebook::react::(anonymous namespace)::exceptionWrapMethod<&(facebook::react::JSCExecutor::getNativeModule(OpaqueJSValue*, OpaqueJSString*))>())(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSString*, OpaqueJSValue const**)::funcWrapper::call+ 10497588 (OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSString*, OpaqueJSValue const**) + 104
11  JavaScriptCore                	0x000000020a45f69c JSC::JSCallbackObject<JSC::JSDestructibleObject>::getOwnPropertySlot+ 2586268 (JSC::JSObject*, JSC::ExecState*, JSC::PropertyName, JSC::PropertySlot&) + 344
12  JavaScriptCore                	0x000000020aa45fe4 llint_slow_path_get_by_id + 3984
13  JavaScriptCore                	0x000000020a42ade4 llint_entry + 31844
14  JavaScriptCore                	0x000000020a438838 llint_entry + 87736
15  JavaScriptCore                	0x000000020a438838 llint_entry + 87736
16  JavaScriptCore                	0x000000020a438838 llint_entry + 87736
17  JavaScriptCore                	0x000000020a438838 llint_entry + 87736
18  JavaScriptCore                	0x000000020a438a30 llint_entry + 88240
19  JavaScriptCore                	0x000000020a422ef4 vmEntryToJavaScript + 276
20  JavaScriptCore                	0x000000020a9735b0 JSC::Interpreter::executeProgram+ 7910832 (JSC::SourceCode const&, JSC::ExecState*, JSC::JSObject*) + 11056
21  JavaScriptCore                	0x000000020ab9c67c JSC::evaluate+ 10176124 (JSC::ExecState*, JSC::SourceCode const&, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&) + 328
22  JavaScriptCore                	0x000000020a45d560 JSEvaluateScript + 636
23  appName                         	0x000000010532b274 facebook::react::evaluateScript+ 10367604 (OpaqueJSContext const*, OpaqueJSString*, OpaqueJSString*) + 80
24  appName                         	0x0000000105348f48 facebook::react::JSCExecutor::loadApplicationScript+ 10489672 (std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 512
25  appName                         	0x000000010534ef6c std::__1::__function::__func<facebook::react::NativeToJsBridge::loadApplication(std::__1::unique_ptr<facebook::react::RAMBundleRegistry, std::__1::default_delete<facebook::react::RAMBundleRegistry> >, std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0, std::__1::allocator<facebook::react::NativeToJsBridge::loadApplication(std::__1::unique_ptr<facebook::react::RAMBundleRegistry, std::__1::default_delete<facebook::react::RAMBundleRegistry> >, std::__1::unique_ptr<facebook::react::JSBigString const, std::__1::default_delete<facebook::react::JSBigString const> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0>, void (facebook::react::JSExecutor*)>::operator()+ 10514284 (facebook::react::JSExecutor*&&) + 144
26  appName                         	0x000000010534fe14 std::__1::__function::__func<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_7, std::__1::allocator<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_7>, void ()>::operator()+ 10518036 () + 60
27  appName                         	0x00000001052cc860 facebook::react::tryAndReturnError(std::__1::function<void + 9980000 ()> const&) + 40
28  appName                         	0x00000001052c2e98 facebook::react::RCTMessageThread::tryFunc(std::__1::function<void + 9940632 ()> const&) + 24
29  CoreFoundation                	0x0000000202f5127c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28
30  CoreFoundation                	0x0000000202f50b64 __CFRunLoopDoBlocks + 276
31  CoreFoundation                	0x0000000202f4be58 __CFRunLoopRun + 2276
32  CoreFoundation                	0x0000000202f4b254 CFRunLoopRunSpecific + 452
33  appName                         	0x00000001052a4cd4 +[RCTCxxBridge runRunLoop] + 264
34  Foundation                    	0x0000000203929c4c -[NSThread main] + 72
35  Foundation                    	0x0000000203a5fe54 __NSThread__start__ + 988
36  libsystem_pthread.dylib       	0x0000000202bc9908 _pthread_body + 132
37  libsystem_pthread.dylib       	0x0000000202bc9864 _pthread_start + 48
38  libsystem_pthread.dylib       	0x0000000202bd1dcc thread_start + 4

**Comment by techistoner** [comment]
finally , i find the solution.
http://peterfei.me/2019/04/10/%E8%AE%B0IOS%E5%BC%80%E5%8F%91%E4%B9%8B%E6%88%91%E6%98%AF%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3react-native-unity-view%E6%8F%92%E4%BB%B6%E5%9C%A8Product%E6%A8%A1%E5%BC%8F%E9%97%AA%E9%80%80Bug/

**Comment by alisherakb** [comment]
@JanOwiesniak Hi, have you managed it work with Unity 2018.3.+?
I'm experiencing the [same issue ](https://github.com/f111fei/react-native-unity-view/issues/79#issuecomment-472617761)
<img width="720" alt="Screenshot 2019-08-07 at 5 28 12 PM" src="https://user-images.githubusercontent.com/26904008/62631052-c5d6b300-b938-11e9-9d1b-1727977c934f.png">
